name: bake
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v2
      - uses: crazy-max/ghaction-github-runtime@v1
      - uses: docker/bake-action@v2
        with:
          files: compose.yaml
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
